<?php
Admin::prep();
Builder::clear();

if(Admin::getLoc() == "passwordReset"){
  Builder::loadPart("admin_pwReset");
} else if(!Admin_User::isLoggedIn()){
  Builder::loadPart("admin_login");
} else if(Admin::hasAccessTo(explode("/",Admin::getLoc()),0)){
  include("cms/modules/" . Admin::getLoc());
} else if(Admin::isInjectedLoc()) {
  include("cms/modules/" . Admin::getLoc());
}

Builder::loadPart("admin_denied");
Builder::end();
?>
