<?php
 $size = "col";
 if(Builder::getParam("size") == "small"){
    $size = "col-xl-3 col-md-6";
 } else if(Builder::getParam("size") == "medium"){
    $size = "col-lg-6";
 } else if(Builder::getParam("size") == "large"){
    $size = "col-xl-9";
 } else if(Builder::getParam("size") == "extralarge"){
    $size = "col-12";
 }

?>

<div class="<?php echo $size; ?>">
  <div class="card mb-4">
      <div class="card-header">
          <i class="<?php echo Builder::getParam("icon"); ?> mr-1"></i>
          <?php echo Builder::getParam("title"); ?>
          <span class="adminCardAlert" id="adminCardAlert<?php echo Builder::getParam("title"); ?>"></span>
      </div>
      <div class="card-body">
        <?php echo Builder::getParam("content"); ?>
      </div>
  </div>
</div>
