<?php global $admin_params; ?>

<div class="card mb-4">
    <div class="card-header">
        <i class="<?php echo $admin_params["icon"]; ?> mr-1"></i>
        <?php echo $admin_params["title"]; ?>
        <span class="adminCardAlert" id="adminCardAlert<?php echo $admin_params["title"]; ?>"></span>
    </div>
    <div class="card-body">
      <?php echo $admin_params["content"]; ?>
    </div>
</div>
