<?php
  Builder::startHead();
  Builder::loadPart("admin_header");
  Builder::loadCSS(false);
  Builder::loadFonts(false);
  Builder::startBody();
  Builder::loadPart("admin_start");
?>

<?php
  function jsonToTable($data, $immut, $hide, $parent = []){
    $table = '<table class="table table-bordered table-editable">';
    foreach($data as $key => $value) {
      $skip = in_array($key, $hide, true);
      foreach($parent as $prt){ $skip = $skip || in_array($prt, $hide, true); }

      $excl = in_array($key, $immut, true);
      foreach($parent as $prt){ $excl = $excl || in_array($prt, $immut, true); }

      $table .= '<tr valign="top">';
      if(!is_numeric($key)){ $table .= '<td class="immutable"><strong>'. $key .':</strong></td>'; }

      $table .= '<td ';
      if(is_numeric($key)){ $table .= 'colspan="2" '; }
      if($excl || $skip){ $table .= 'class="immutable" '; }
      $table .= '>';

      if($skip){
        $table .= "<i>HIDDEN</i>";
      } else {
        if(is_object($value) || is_array($value)){ $table .= jsonToTable($value, $immut, $hide, array_merge($parent, [$key])); }
        else { $table .= json_encode($value); }
      }

      $table .= '</td></tr>';
    }
    $table .= '</table>';
    return $table;
  }

  Admin::addTitle("Config");
  $conf = Admin::getConfig($_GET['mod']);
  $items = [$conf->name, "Config"];
  Admin::addBreadcrumbs($items);

  $immut = [];
  if(isset($conf->immutableKeys)){ $immut = $conf->immutableKeys;  }
  $hide = [];
  if(isset($conf->hiddenKeys)){ $hide = $conf->hiddenKeys;  }
  $path = "cms/modules/" . $_GET['mod'] . "/config.json";
  $content = jsonToTable(json_decode(file_get_contents($path)),$immut,$hide);
  Admin::addCard($conf->name,"fas fa-wrench",$content);
 ?>

<?php
  Builder::loadPart("admin_end");
  Builder::loadJS(false);
  Builder::end();
?>
