<?php
  Builder::startHead();
  Builder::loadCSS(false);
  Builder::loadFonts(false);
  Builder::startBody();
  Builder::loadPart("admin_start");
?>

<?php
  function jsonToTable($data,$excl){
    $table = '<table class="table table-bordered table-editable">';
    foreach($data as $key => $value) {
      $table .= '<tr valign="top">';
      if(!is_numeric($key)){ $table .= '<td class="immutable"><strong>'. $key .':</strong></td>'; }

      $table .= '<td ';
      if(is_numeric($key)){ $table .= 'colspan="2" '; }
      if(in_array($key, $excl)){ $table .= 'class="immutable" '; }
      $table .= '>';

      if(is_object($value) || is_array($value)){ $table .= jsonToTable($value, $excl); }
      else { $table .= json_encode($value); }
      $table .= '</td></tr>';
    }
    $table .= '</table>';
    return $table;
  }

  Admin::addTitle("Config");
  $conf = Admin::getConfig($_GET['mod']);
  $items = [$conf->name, "Config"];
  Admin::addBreadcrumbs($items);

  $excl = [];
  if(isset($conf->immutableKeys)){ $excl = $conf->immutableKeys;  }
  $path = "cms/modules/" . $_GET['mod'] . "/config.json";
  $content = jsonToTable(json_decode(file_get_contents($path)),$excl);
  Admin::addCard($conf->name,"fas fa-wrench",$content);
 ?>

<?php
  Builder::loadPart("admin_end");
  Builder::loadJS(false);
  Builder::end();
?>
