<?php
  Builder::startHead();
  Builder::loadCSS(false);
  Builder::loadFonts(false);
  Builder::startBody();
  Builder::loadPart("admin_navbar");
?>

<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center mt-5 mb-5">
                    <div class="col-lg-5 mt-3 mb-3">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header">
                              <h3 class="text-center font-weight-light my-3">Login</h3>
                              <h6 class="text-center font-weight-light" id="loginMessage"></h6>
                            </div>
                            <div class="card-body">
                                <form>
                                    <div class="form-group">
                                        <label class="small mb-1" for="loginEmailAddress">Email</label>
                                        <input class="form-control py-4" id="loginEmailAddress" type="email" placeholder="Enter email address" />
                                    </div>
                                    <div class="form-group">
                                        <label class="small mb-1" for="loginPassword">Password</label>
                                        <input class="form-control py-4" id="loginPassword" type="password" placeholder="Enter password" />
                                    </div>
                                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <a class="small" href="password.html">Forgot Password?</a>
                                        <a class="btn btn-primary" onclick="login('loginEmailAddress','loginPassword', 'loginMessage');">Login</a>
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="register.html">Need an account? Sign up!</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
    <div id="layoutAuthentication_footer">
        <?php Builder::loadPart("admin_footer"); ?>
    </div>
</div>

<?php
  Builder::loadJS(false);
  Builder::end();
?>
