<?php
  Builder::startHead();
  Builder::loadPart("admin_header");
  Builder::loadCSS(false);
  Builder::loadFonts(false);
  Builder::startBody();
  Builder::loadPart("admin_navbar");
?>

<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center mt-5 mb-5">
                    <div class="col-lg-5 mt-3 mb-3">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header">
                              <h3 class="text-center font-weight-light my-3">Password Recovery</h3>
                              <h6 class="text-center font-weight-light" id="pwResetMessage"></h6>
                            </div>
                            <div class="card-body">
                                <form>
                                    <div class="form-group">
                                        <label class="small mb-1" for="pwChangePW">New password</label>
                                        <input class="form-control py-4" id="pwChangePW" type="password" placeholder="Enter new password" />
                                        <input id="pwChangeKey" type="hidden" value="<?php echo $_GET['key'] ?>"/>
                                        <input id="pwChangeUsername" type="hidden" value="<?php echo $_GET['US'] ?>"/>
                                    </div>
                                    <!-- for some reason removing this form group causes enter to direct to homepage -->
                                    <div class="form-group" style="display:none;">
                                        <label class="small mb-1" for="loginPassword">Password</label>
                                        <input class="form-control py-4" id="loginPassword" type="password" placeholder="Enter password" />
                                    </div>
                                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <a class="small" href="?loc=admin">Back to login</a>
                                        <a class="btn btn-primary" id="pwChangeButton" onclick="changePW('pwChangeUsername','pwChangePW','pwChangeKey','pwResetMessage');">Change password</a>
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
    <div id="layoutAuthentication_footer">
        <?php Builder::loadPart("admin_footer"); ?>
    </div>
</div>

<?php Builder::loadJS(false); ?>

<script>
  $('input').keypress((e) => { if(e.keyCode==13) $('#pwChangeButton').click(); } );
</script>

<?php Builder::end(); ?>
