<?php
  Builder::startHead();
  Builder::loadPart("admin_header");
  Builder::loadCSS(false);
  Builder::loadFonts(false);
  Builder::startBody();
  Builder::loadPart("admin_start");
?>

<?php
  Admin::addTitle("Readme");
  $items = [Admin::getConfig($_GET['mod'])->name, "Readme"];
  Admin::addBreadcrumbs($items);

  $root = ModMan::getRoot("admin");
  include($root . "parts/Parsedown.php");
  $path = "cms/modules/" . $_GET['mod'] . "/readme.md";
  $content = "No Readme found";
  if(file_exists($path)){ $content =  Parsedown::instance()->text(file_get_contents($path)); }
  Admin::addCard(Admin::getConfig($_GET['mod'])->name,"fas fa-file-alt",$content);
 ?>

<?php
  Builder::loadPart("admin_end");
  Builder::loadJS(false);
  Builder::end();
?>
