<?php
  if(!Admin::hasAccessTo($_GET['mod'],0)){ Builder::loadPart("admin_denied"); }
  Builder::startHead();
  Builder::loadPart("admin_header");
  Builder::loadCSS(false);
  Builder::loadFonts(false);
  Builder::startBody();
  Builder::loadPart("admin_start");
?>

<?php
  Admin::addTitle("Readme");
  $items = [Admin_Config::getConfig($_GET['mod'])->name, "Readme"];
  Admin::addBreadcrumbs($items);

  $root = ModMan::getRoot("admin");
  include($root . "parts/Parsedown.php");
  $path = ModMan::getRoot($_GET['mod']) . "/readme.md";
  $content = "No Readme found";
  if(file_exists($path)){ $content =  Parsedown::instance()->text(file_get_contents($path)); }
  Admin::addCard(Admin_Config::getConfig($_GET['mod'])->name,"fas fa-file-alt",$content,"extralarge");
 ?>

<?php
  Builder::loadPart("admin_end");
  Builder::loadJS(false);
  Builder::end();
?>
