<?php Builder::loadPart("admin_navbar"); ?>

<div id="layoutSidenav">
  <div id="layoutSidenav_nav">
      <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
          <div class="sb-sidenav-menu">
              <div class="nav">
                  <div class="sb-sidenav-menu-heading">Core</div>
                  <a class="nav-link" href="index.html">
                      <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                      Dashboard
                  </a>

                  <div class="sb-sidenav-menu-heading">Modules</div>

                  <?php $count = 0; foreach(Admin::getConfigs() as $conf){ ?>
                    <?php $currMod = explode("/",Admin::getLoc())[0] == $conf->mod; ?>
                    <a class="nav-link <?php if($currMod){ echo "active"; } else { echo "collapsed" ;} ?>" href="" data-toggle="collapse" data-target="#collapseLayouts<?php echo $count; ?>" aria-expanded="<?php echo $currMod; ?>" aria-controls="collapseLayouts">
                        <div class="sb-nav-link-icon"><i class="<?php echo $conf->icon; ?>"></i></div>
                        <?php echo $conf->name; ?>
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse <?php if($currMod){ echo "show"; } ?>" id="collapseLayouts<?php echo $count; ?>" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                          <?php foreach($conf->links as $link){ ?>
                            <a class="nav-link <?php if($currMod && Admin::getLoc() == explode("&",$link->link)[0]){ echo "active"; } ?>" href="?loc=admin&admin_loc=<?php echo $link->link; ?>"><?php echo $link->name; ?></a>
                          <?php } ?>
                        </nav>
                    </div>
                  <?php $count++; } ?>


                  <div class="sb-sidenav-menu-heading">Addons</div>

                  <a class="nav-link" href="?loc=admin&admin_loc=logger/log_admin.phtml">
                      <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                      Charts
                  </a>


              </div>
          </div>
          <div class="sb-sidenav-footer">
              <div class="small">Logged in as:</div>
              <?php echo Admin::getUser()->username; ?>
          </div>
      </nav>
  </div>

<div id="layoutSidenav_content">
    <main>
      <div class="container-fluid">
        <div class="row">
