<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a id="sidebarToggle" class="navbar-brand" href="">AMS</a>
    <!-- <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button> -->
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
            <div class="input-group-append">
                <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">Settings</a>
                <a class="dropdown-item" href="#">Activity Log</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="login.html">Logout</a>
            </div>
        </li>
    </ul>
</nav>

<div id="layoutSidenav">
  <div id="layoutSidenav_nav">
      <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
          <div class="sb-sidenav-menu">
              <div class="nav">
                  <div class="sb-sidenav-menu-heading">Core</div>
                  <a class="nav-link" href="index.html">
                      <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                      Dashboard
                  </a>

                  <div class="sb-sidenav-menu-heading">Modules</div>

                  <?php $count = 0; foreach(Admin::getAdminConfigs() as $conf){ ?>
                    <a class="nav-link collapsed <?php if(explode("/",Admin::getLoc())[0] == $conf->mod){ echo "active"; } ?>" href="" data-toggle="collapse" data-target="#collapseLayouts<?php echo $count; ?>" aria-expanded="false" aria-controls="collapseLayouts">
                        <div class="sb-nav-link-icon"><i class="<?php echo $conf->icon; ?>"></i></div>
                        <?php echo $conf->name; ?>
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="collapseLayouts<?php echo $count; ?>" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                          <?php foreach($conf->links as $link){ ?>
                            <a class="nav-link <?php if(explode("/",Admin::getLoc())[0] == $conf->mod && Admin::getLoc() == explode("&",$link->link)[0]){ echo "active"; } ?>" href="?loc=admin&admin_loc=<?php echo $link->link; ?>"><?php echo $link->name; ?></a>
                          <?php } ?>
                        </nav>
                    </div>
                  <?php $count++; } ?>


                  <div class="sb-sidenav-menu-heading">Addons</div>

                  <a class="nav-link" href="?loc=admin&admin_loc=logger/log_admin.phtml">
                      <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                      Charts
                  </a>


              </div>
          </div>
          <div class="sb-sidenav-footer">
              <div class="small">Logged in as:</div>
              AMS
          </div>
      </nav>
  </div>

<div id="layoutSidenav_content">
    <main>
