<?php
  Builder::startHead();
  Builder::loadPart("admin_header");
  Builder::loadCSS(false);
  Builder::loadFonts(false);
  Builder::startBody();
  Builder::loadPart("admin_start");
?>

<?php
  Admin::addTitle("Users");
  $items = ["Admin", "Users"];
  Admin::addBreadcrumbs($items);
 ?>

<?php


$content = '
<form>
  <div class="form-group">
        <label class="small mb-1" for="addUserUsername">Username</label>
        <input class="form-control py-4" id="addUserUsername" type="text" placeholder="Enter username" data-entertrigger="userAddButton"/>
    </div>
    <div class="form-group">
        <label class="small mb-1" for="addUserPassword">Password</label>
        <input class="form-control py-4" id="addUserPassword" type="password" placeholder="Enter password" data-entertrigger="userAddButton" />
    </div>
    <div class="form-group">
        <label class="small mb-1" for="addUserEmail">Email</label>
        <input class="form-control py-4" id="addUserEmail" type="email" placeholder="Enter email" data-entertrigger="userAddButton"/>
    </div>
    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
        <a class="small"></a>
        <a class="btn btn-primary" id="userAddButton" onclick="addUser(\'addUserUsername\',\'addUserPassword\', \'addUserEmail\');">Add User</a>
    </div>
</form>';
Admin::addCard("Add Users","fas fa-user-plus",$content,"small");

 ?>

<?php
  function userToTable($data){
    $table = '<table class="table table-min" id="userTable">
      <colgroup>
       <col span="1" style="width: 10%;">
       <col span="1" style="width: 30%;">
       <col span="1" style="width: 30%;">
       <col span="1" style="width: 15%;">
       <col span="1" style="width: 15%;">
      </colgroup>

      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>Email</th>
        <th></th>
        <th></th>
      </tr>';

    foreach($data as $user) {
      $table .= '<tr valign="top" id="userRow' . $user->ID . '">';
      $table .= '<td>'. $user->ID .'</td>';
      $table .= '<td>'. $user->username  .'</td>';
      $table .= '<td>'. $user->email .'</td>';
      $table .= '<div class="modal fade" id="userEditModal' . $user->ID . '">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title">Edit '. $user->username  .'</h5>
                        <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button>
                      </div>
                      <div class="modal-body">
                        <form>
                          <div class="form-group">
                                <label class="small mb-1" for="editUserUsername'.$user->ID.'">Username</label>
                                <input class="form-control py-4" id="editUserUsername'.$user->ID.'" type="text" placeholder="Enter username" value="'.$user->username.'" data-entertrigger="userEditButton'.$user->ID.'"/>
                            </div>
                            <div class="form-group">
                                <label class="small mb-1" for="editUserPassword'.$user->ID.'">Password</label>
                                <input class="form-control py-4" id="editUserPassword'.$user->ID.'" type="password" placeholder="Enter password" data-entertrigger="userEditButton'.$user->ID.'" />
                            </div>
                            <div class="form-group">
                                <label class="small mb-1" for="editUserEmail'.$user->ID.'">Email</label>
                                <input class="form-control py-4" id="editUserEmail'.$user->ID.'" type="email" placeholder="Enter email" value="'.$user->email.'" data-entertrigger="userEditButton'.$user->ID.'"/>
                            </div>
                        </form>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" id="userEditButton'.$user->ID.'" onclick="editUser('.$user->ID.')">Save changes</button>
                      </div>
                    </div>
                  </div>
                </div>';
      $table .= '<td><a class="btn btn-primary btn-sm btn-block" data-toggle="modal" data-target="#userEditModal' . $user->ID . '"><i class="fas fa-pencil-alt"></i> Edit</a></td>';
      $table .= '<td><a class="btn btn-danger btn-sm btn-block" onclick="delUser('.$user->ID.')"><i class="fas fa-trash-alt"></i> Delete</a></td>';
      $table .= '</td></tr>';
    }

    $table .= '</table>';
    return $table;
  }

  $data = ModMan::getConfig("admin")->users;
  $content = userToTable($data);
  Admin::addCard("Edit Users","fas fa-user-edit",$content,"large");
 ?>

<?php
  Builder::loadPart("admin_end");
  Builder::loadJS(false);
  Builder::end();
?>
