<?php
  if(!Admin::hasAccessTo($_GET['mod'],0)){ Builder::loadPart("admin_denied"); }
  Builder::startHead();
  Builder::loadPart("admin_header");
  Builder::loadCSS(false);
  Builder::loadFonts(false);
  Builder::startBody();
  Builder::loadPart("admin_start");
?>

<?php
  Admin::addTitle("Logs");
  Admin::addBreadcrumbs(["Logger","Logs"]);

  $root = ModMan::getRoot("logger");
  $path = $root . "/logs.txt";
  $content = "No logs found";
  if(file_exists($path)){ $content =  nl2br(file_get_contents($path)); }
  Admin::addCard("Logs","fas fa-file-alt",$content,"extralarge");
 ?>

<?php
  Builder::loadPart("admin_end");
  Builder::loadJS(false);
  Builder::end();
?>
